---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: he-credentials
  namespace: external-dns-public
spec:
  encryptedData:
    password: AgCDXdXs73ySaPJKza8w7DnnRXs1DdChBydifutsYjXDO4fY3SJcHuztbNaJ1VVAzB7vFzay0i73c+0YIWunk38oBozrON0PlUFSIJsvaWsRFK54U8gYh71ZzXO9B1XakeJNG8kcV8Ua6E5f/Cb5L4xcX3gDyJ80aPjEcyLE9oQkr0rcJVUtgMkxgCtyWnBbudRrhjpbjDxRKDl3qr2cmZaF58QOfa5gRUTcwmWpZewrF2i8QfhddJ6yThry7DJaVtfdEQG9EaeCNGQ/UMfBLoUqBrGcuPOc6pSBpqqDiEkMYFUII1OnlKpSp+ldFVZ07wFhOE2qrIe1CvmLwU7tG9olPOfmZWjzVTvLvxY5dwXQrJTegfgIwT05cX9YgYcbyDVW6tAN+w7W6jl98WBIJOo7tZwdqkQam6hR0/9UPoeuaV1/VPx+gbfguYObmGRUDe1q2LsZFF7TG3U/P0XMfmUKY1TyDtuzlXRks3kB6wLzGfwTJgEhrnuHyHP29wC206psk8xFHLxclZeORlJpQ50bg3tI02H3ZtR2sWg6Uscl5JnwT4IlKPiYkPBiYaZHNQ3jqLgZVddMvdOWpAr1G+XXG4qkxIa4ZcmiOOfBznV3Yx/4bv5sNp5q5IZGP1mDcuydM1/hYjfJPucCrV+dwPo5lmh4RB3nZeN4qHjgEq789/nkVkawVq2r9I4m3wPzlQnPvBU/mdjYO7Lb59fkjr5Q8tk=
    username: AgDEwkzpbKODxh660rfkpUIJvyV0yzTlkW09Hj7RcOXMytpPxwzYWC7EKHkE9Uy4GMplnV06vXR+82a7seIAfxbhfE/0OCJc22vSbIDI7n+9GjvdUv0lPtNZNaK8gNcedyBCGJz6Lr7DNXJiUCGG0Hx3r+KmvJLQGDrf8TD8ZLyIyLAeX+3u1ZWpRthrewGDujSIVgHTQd0Y6mwwIS840dUr4hSPKAMGenSaYz/zZS3FrFteakgC1gkpmZsqcwWaPe5MEwaWWoHla8fBK9tas1DERue2GLImhz1d1DinDmG0dd9dY05l06hnQLlLk/5jt5RjqNx2PRf9vhBLtHO/dys5+mc3sTfLh95aMQusY3UY5eT6vfY2hmtPZnDhQEuMEXmww4QXuoAChuFQIGFTCwCfISiTBeYEP7yhfCflFZUcZ9oTS1aC/IQkpo3Ev8+xXz6oHjeW/WRdoaXAEPNP0YvZ5jM9AMYY+3gLg+0ICeGGPyBhzxA12Y3ExGlEcLsJAMurxcYIojBmN/hHSU24cREPOOw3yyrOEz5FFezuDHbDbSo+nySXdP7DaeFItkG1fvRx/ChW/I0foLHCT+twx2g9Abz/f8uuJjH+5jx70edWv5ob6d0PL+0RBxYgWU5IapsephukCSZHu0wb6qNDRgY2ezqvFpHQ9fKvVG7kFdUdhs3mFfcU0JWZ2mDqhk3ekxezTfoyWs2dMA==
  template:
    metadata:
      creationTimestamp: null
      name: he-credentials
      namespace: external-dns-public
