---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-auth
  namespace: ai
spec:
  encryptedData:
    master-key: AgBT4TNMH2wvnsdpL6vrkETzWmDEnPNN0qb1eNT2sWJ/MV/dJW3B1PszdUemPE8hzR/UndYwOXJDYwkfhe85AgcBLqjw4/sQR+qVemTFqkJE18I4RGLWR/7q/Dm7nKUvBe+ntSPGSwwmnyWxj5c/Ts09Xe1Tl3MjKX5+69j/xiQEel6z4cZGXr9D2+T+wUp34RewS1WYtNRGxQfpA5uR0ZbGA+M8kxJkPpUV1d6E1YCT/0Sigd5yc64R/7c047J2uAeSqzjbGmG5spTwCo/qLbPgqimKfJj3nkHP6SR9XO7mixkGBAwBn0VfYNQoqYLEJayVFmayiaCfdlJ6fQAbGqdWzb0YhfZB5Z8HIxvkjFYL2yKFPzAAKLTli97Ew4JtZC3EL+QgIaiCUC9xULhiY2gMEyFVg/3K/bu/yQPTZscuh5fzTfKwflLfQoWzlqBGQ4uSP8ycNlIiHkc1CrGLms8Rer2zcmdgnmInnFwhEAtXqRygeoJzebOHt0lxkORlIseyes9Tk1DmBfAipkKFiArPyO3G25WQmuf5Ltgk5z7u+gOO5SRhj2Rb6mlR0mCwF0ZJUH0R/tETOeRgRHvz8NXkyQOmCA4I/aX09G13A/3rw+TGu/GG2kPq/5kVy1BlcX6H1T7ho5PTYl5TspMAX1Ol0667p7mD2R+pykkShInv6YKA5tSf12p3CuMS3k9Ivuu5S0PXbbZqKNYSSPYE7ZviEqEFiC3iwqY9wRDltQAVc1qmxT3TJMPl
  template:
    metadata:
      creationTimestamp: null
      name: litellm-auth
      namespace: ai
