---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oci-registry-auth
  namespace: ai
spec:
  encryptedData:
    htpasswd: AgC2fE+H+9RLYjhqEVpKSDgZK2hn2iXBZIUEMwkcG2sef9lmohwJXlPcXA/SkJcXXnug11ZWb8CNtqOKVPRXTr7XPrincvHap1DKXVmdohO/GLleYVE6U9AG0vSO1uKd/IVe1KiTepxdC3p9biuP5HFWQ83JLWf6bkk11N0sTwIkTUdT74EzRKQP6fa6YFSSMdiENJ6Lo/kSEaaGrkYnujAnbTLkWlfDtBTEQE4DTvQoKwrBml9L8omuvXaogpjDozySP3F5YJdoWphoS1runXX6G0Rg20YSpyj17MD+Z+K7Vq3Xi2130KlF6xhoWitKhmnri1VD1plKmiA1V12V0tiMBGX/1NvNG9I/h0QG+F2zt7UTz+wjATgi/gPX5Laog6L8JddoZRvo3BIBfW8vQPEf5OuDNpMLhJI1HNMtJ8CSyqNgm1frErwUL+CmuHqoFTfv5L4bhQg9Ybzrvz62kKctPfWNPkAEtVvm7WVLdRqiaS2BSu5VE3rwF4vz3Z8NAN7ksJNcsxtwp3O7uehiYWxJ12+y5VuBOzKiX/6jXrXMVEUXuiDEiPR7vNK+PYT+izS8yPIsIhg7Oqtl5THnApUHwUGw2e8LWP0LwFsPrvdfXEd7d/495Vf82LCFGGVX3ducx+4IpvlCdGEzEJU4PLfH3YqGGrpQrB4uS57mjtpVC+UX1UCoUuKi92IZsQALi+6Qnd6NrExGX8+1k6vEHfMOzIBxMk3jSiDNLzaxnfBHDrWH9DQtvJz9D1e1o3h5whwyotGedgxF13U9GKEMDmE6sa2YzF0=
    http-secret: AgCiS6QQXwQLG1U+B9JRxTN4pB+KvN03H+sn4EXMijcZygyEOTZ7axF2OaS2mJ7oVwK835X/bSyhygOtM3K4ycE1muUtcpOsZLwkcVJQ0zkfP/jNvZqZFJzSDyG9L70yB/wrJ7hp9zwuixy+OluJRFSoI3Q6aMbjVAuBy5Il4ZZpxGF7webMyKRuELNkFZt3gKSXTu4EITicMN89DffCC4VLXC3LRxlKYKQHEva0uo3utUnDTOoVoJkH6xKUvKonCyGnURySRymng7w7zIw/guCGGm+p2GkLWFcg/nsR/UbIgnrDnLuJ6gFCnSdCzfSo7e1d9UOajps/NPRy3F5SuiEP6m/QqxDA0eB5xwjIa2EyuZsUIrwsscNbP0iiu90cZfQeiUZ6lTwPQjowyPrYdgH9BNQs27pwEoHmTIIHCiuelNRfm9tqvZxfr37MLwmYVLSKB+d5vXMlJ9wa6HARo9N0Gf2FpcUWWiYdJvrRnpm5DJJs2uzubD4CMsdMbDV6ntktj1/dCDgC6EVkW6gdZTXmrxBCSCAE8hn6HpV5w3MmhJx4rHSXf4Tce3NK1ypKNv2JCsvDQMHzi3SzVFUTWNVJPcPHM/VAN07kuvktVM9YyfWHtdbMAwGKSG6JtaTEwbQRZb6YD4VAu604u3DQEkZP4ZW5tDwPJK4rysMUMr2Z5yWoMwsalMXBG0Z67PNndo0EF7FVMs+eg3jrDul5M/rNgWUW6YH9ELluzK+WwTdR4GFjOawRpeLXrbOYlogOlhbKFoZQJO8cLBaBPHc7eUPH
  template:
    metadata:
      creationTimestamp: null
      name: oci-registry-auth
      namespace: ai
