---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-env
  namespace: wavelog
spec:
  encryptedData:
    CI_ENV: AgDB06ozvj23l4a6RCJYimLxrPIwmVgI3iyhecoeZeweeIyVfY2zHiUVtBMuxcTQ2YdgoNL4n40bPjxt7EQ80blKZYOjeZZAcKkiaN84Ztc8DfeIrTawi0dJmhtjTVSloE+/AlsFcVrWl21IgSXjMWNPauQ0Pvc82O9Vtn0D9diu6KZoShu3YrOFCJ5rNLYs0Ed0G8VVgG9IUbhtAxXFrhy9PfLf6RoNwDv4HZheSCuYj3dbeueCeempOcnVPfwWFETL6BHNh4z73lgkdv5dmH7NuJ4k1M7y6+Bz5gKVIgAlqONC3PktAwJkUhVoeqGG3NLujH8Ee5h3fm7ccoEbuwhh7YMBdK0RWbYqBmywK04R7LWEW+JsmzYI6fDgH8tTGHRyPXT6jfza4H2PINzXCrYHOdsOp/4HwdJXED1WiStFX9F5GWP1A/uB78HrqvXGF7UW/jdAnRrXVmdxrVT6XozhRCTFeMBI0N+hZh/Ms4naF5ngq7nPP+7vHYnkgVcivnIXOG6FKpFPDLaw2WH8mCmkkZSmbNOqWKB1g+xYINqwsKfkWvXjxMXhVd/EhEVULYqs/tcgluERe1+5QuWcyjaDFWp0A4M/KLhoajS4WcIc/JqZB1xRDQIINaJYZsilj+h5JkDeCDRByn7L24u6tGdO4lOVkyUMvo2QJCNwIZNsHZOK2C5PH+LlDfK621Shy/WuYknBiU4=
  template:
    metadata:
      creationTimestamp: null
      name: app-env
      namespace: wavelog
