---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB9zrxCuqm1/wB+BZtpVjEJWo9QHoPNRRyjzDnE48Q9twXNJfxxSkIP8Q5GpjSu594PZ90jopjje7Lwp7otutwF5xKKZdxnMcnMIgCxlv5c17yaSIWnYCYr5C/OnRANy8jMOb7jocpGF5awaodDFYiNpC7kVmf4uE9zBjyIsKacH/OqsWgD6h+Of7rIblx/GCxcmZP3h9ppO1djclTX71avgIAwjFBx/oDlnhX2iQ1BhWlYl0TBInIN9uBxieeVf5IluEDAYV3ZNylj7bQqVJwhQVViWNJCM0mNDDcxB9vW55kGRBZECrUn3FoY3MNnelwiYfJPE/nnLf9hzY338r/1htadphTI1auesKePUhwH3IcipB822sojd9wwaRQdCtXfe1j2yxXHmAl0GwWpWr+DC5KW7j3Nh1ZB3neTWIly0t3Te/Ar9JtAr+c1dVvLJD4csEeI2VJY+SPa6VQj7XHYVFUxvIwDGfxpI8jR/tIKXNdOstpgQ2HjISUmvdOd7o3yc2c62sC8aOFL0fub0GTxXZ42bSnOqY9JNjWmkChTLNpixoxBEvUkduIIZWEg2p9S5+ux7/gvv80ov3o9Nx5Q2xfvbLn04TBqQHdm+80QNHbZqt9H22xMnKUbdSEDfciHg45VQ+bvpzuNk51uRy9bbJQsmBLEUP155otS4mWvWJJQCksNvkYkc7oIWsRzz6z382df12GPGpMrbO2AsNmTUQHD44eYQccEijcAacT3IqlCCZyzlRQKog9s
    admin-user: AgB0o2VdI1zPtqTYtd5mQZcm60NNbwz2beosUiH07pmdpn493r2zvzpK3b3izF4Achx1qvSDs4SvVdjdVmJJkL3T3AKDPUAbYlT4PjJ7zg5sBDd2h/ShUlwp6OtMRjDIKyAW9Tuq9sg1iB6OSjgdD900SbZJMdxZPMalUposY2wTkWNGCBdu3NCmnlW/QFS4HfWEC39QDOcx+1hDY7hbwYD25Ag4TzBlZDxWOhD2CVb5x4/vEssbNT/OHMXVvw/thJCHnUkB7WWikELuexDmlZOv+7fcuhyAmr6Ly4TaxkWzhkhS8mBTO4mHpZ56vU1y+CPlcjwzs9CwOtnh5BtllVm8N7io38Y1hXo6esdjovtPn0KZxQhgO6oChmg0Q37VGNz7BMNNpAT4u+yjrEjLXXI6SyEIIs+RxAGA5oovWiKRsPfC5+3mW7mDcv+EGE3q2ACI5jw2lg1yp+Mn2U+wN8SdOPtx7h/Km6fRdrHwVflWQzdEza2bjXmzMktxLFani3Hh7tyoGKS3rqyGK4MeWeeL00QhpAy6hd3dScUyvM5w7L6xDjP8a8458kvY4+O2jFMElhuGGFs56Ui+JDwEctrMzt3aItPKRxeYfzLjZYMOIBksjGfjl79/VZ1B7ijZKdwlVY+l7OaE0gWA+h3bK88LBlZJlExxssCCGty2gPAHISlcYGIoO77Obm9L2Mr22GT9JFiCuw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
    type: Opaque
