apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  namespace: karpenter-nfs-sample
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-nfs
  resources:
    requests:
      storage: 1Gi
