---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oci-registry-pull
  namespace: games
spec:
  encryptedData:
    .dockerconfigjson: AgBOKkCl5TjJokubAXF+M8DLP4lrZWcEu995ghzX/crbDqzyRr1qw664gGCWsH+RJBC05e4bXcm9HXyiOQYPvs9uE681syCYzN0TXgsdlJh63m0wcoHADa7LSFYZJViiKe4mvYcFrKitwxQsPKdGCLVlJQNmeaUHQrmdwTp5ANk+PHcnnII9jmyLhdCm1zxzZzIS4MdMz1vLWUAas6fmbsRZXt9WJUGIqRowISr9qTmzEKt/0l3SViKjGfJBLxT3v1VcY9b0af8InUs9k3lTYxlxjKE0/wIADwOnaaVQuUNy4PRSfOvLhqCt0xazSNJ57Qlba9vugrDL6VfphmxdblVbpcObsgFbP3cnwMXivBgrEtI6llrqd+K1doun5IMo3T3t6wX55FLwDPzr7zryjvAsXUgTaCSZuKgaaeFqN1aDBl1nCnMV955Rpu2VcyWrwV+hDYnUXKUW8cCR+CHwFvfA1Ca4enxWgHQ9hFz+yWiEDHdiW4AdM4IzF8y+n7sL1KUASwo5t1ga2pJYovowzzSuS1ttJUgMzcytxEzXXHS2SSN5fyLeR85wpWqc2MZ0GjBPRtg8rj9971k0KtBvHO0GBm9fYli/c1QsK50ei68dn/K0LHKTl1u3ri6ixoaMR5yYTuCRyhFaMi6wRpc1XStcTHRzZycX8ggfwbFv3WujGawgcfeOz7G3HVrpbLpVdfc/BpMB+XBpToQgobNaPCShV9l1i7Xk30krIsJjU0vO1r92aRfuFqtb3ZmOUpeYRzeD+V8nLXOFzsfVGCETQZk7wbgGEZ6EyE3sAU8oaxYafzOmruCzzLXAuI4g4TWuuFi1SG3OIdrXzW+HhSjOt2FdDXqZ29QMHzuTx5orGpyB8G3AK+8MRGZL4pABhnaAy9xUH6j2Ml+0nGvFIt6xERc6xjo5HU8bafXAqbEyDA7bnz6GmO0pgNfp5lc32ks=
  template:
    metadata:
      creationTimestamp: null
      name: oci-registry-pull
      namespace: games
    type: kubernetes.io/dockerconfigjson
