---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ceph-csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgCWtp5HyJyVGXGUmRJx2Y3LJxw9gsM+hvBh37FecjAYqU5qi5ALUpxjM6+zj/WbULQJbYsFeWtcuyOgen8i/MBTtVBYjlYj3Qj2Za66X2yEUpOq1MqOw++S9VXoD9eDkbjIKFCdvR/uCgQLfc8NEBEnsUAYDNykJErUFcau7WBfmU41BzYXS0mDGxK9NRKyhCqCGdqOD7tGQval0MRDsh4eBwMTi7NMyd9dIZYFcMG+xqNRA0bm3u3+NdHA/9+lbWTq9v3XScdJnIexPKVfNnwM0H1hOjA2ozxT93UhyEnnaAAUG2sXNtwrbrB8WtnFxdifduHtPaGb19uh4gQfejexqow1EmCyS95TE8ZC5s8xpLLe7yvIQXQiTTFniLAAOY1kaQk/7MLCtFGf9i79vhYMzHJY0KKgT6BMESKa/VO54jchGV9F9rLnOEOFNQuDKtpL0Ssl9obILhM0BAJP6RyzKlygwM+T1BlzBywjxypGP2PDTrRHffpuU9zzXemgWJbpnfWpGBjplkICyg0AhSwhsn+kLhxJVXdAYZ5cVN2tdqQ5UwK5xP2JKHqAxxDCqjUxECu80/82gZeYL5eKTTS6SY8ETJ9WqLYapanmaaTRmUAvNPH7vQPsSxuCluNL2BtuHepDFZO1ZG9CUapn2YyQVzrO/ZW1fzY/IwvsFzfxr9cdv858KWFQcaWa+e8Rm4x0NrE7j2FPa4+bKxwVIw==
    userKey: AgBX5mJD36ZmkLUTfbr4Tn23wkl1xFsVPsPlAHuXT7Q7Or9NF7ZgtKjCFBza3KcnyJi0KH9MpaHIy0fc6ua8Z38utRtkTLgOHIP7FGMtzNmeckPvZDR2Rb5U9ZhfylDrS64Zq6awc1Y6LadYWsOcpdL8RDNAA3Dlf8hdsUC0msNScn/slQ1UNWEpB2DBdjtrRDR3r/72tsyYIodlxr2F7T4EOp1CF21yZAELWw3PbytY1BVd2kXtAOhQi+CpsAOQe6F27CKDakQ1ASMk6qaykr82lespj5NAUrQl1z1/NxNBFdvjbXtudSjQKnVI8HQE6FGkyiEaWzZe2VkyBsj/8HlaGtfZxw1h1ZOtEomjcR7mFhWXcr4NtovU5Z6JzP05RsuWL15QeWB4WbDElLjO4EWxAwZ98leXduFv0aPbCjWEqLme97KFvAjTGWXBZxiMRBWgGZHy0964JwEclY5KArC8ZYPY7eDFU6upz3p2cIpUVPkkRZ6F6OygmDYNIh29KpWIGJYAgDciWNSgutRxvnt0CHh5VkrJdz5XdJK3mQcGegADd8/c+El1pXj7sZKHWh2T2Y7obGYpnvGbBIds9vt80768iw8hwI9orsilZ6ryhEg3onKnh8mtYQ7T/4+TziRNqxhLsqVGAnLBY5bS9w6S25/tT0rXWbY1yZUvZlWx8riw0VkHm0qMNP4DMM8ZBuAZDtcQdgVVHpmrRxpRA/dRTmQvqWcPHKEQpF+G8D9dJ657Q8JBmk1r
  template:
    metadata:
      creationTimestamp: null
      name: ceph-csi-rbd-secret
      namespace: ceph-csi-rbd
    type: Opaque
