---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flux-huggingface
  namespace: ai
spec:
  encryptedData:
    token: AgBM7ZEPayM1DCLzzyrEQ/IkO6eVQoyL+NK3UDdZWBvzzQgDVsVBm31wb2Y4C4iWUeVaJLZrYQUgIR5SmSgG30G0HsIVeePjzuGWuLPhMbA3yNMv9Pl4N7vhM344s9b7v38nSI9H9mts3bdf7mqHXRWkWpCSbtAOuk6wP87aJPwCPPWhThYD545K11vCgIY2W2PUrQeNNzkxJA+W8cQDz+PkVS2b1qtSils6xUft0vZJq65p9GqUHWeC2sgayZ9Qd3v+OIA/BSQyb2zbdZDSi4M/fe4CeWiXOg/v5HBnQEAHb1FBg/KQUeXJ3xyFJAuAtsj85cuAys8dg4d90ZpmI33HceqqGSi0jSrpn4YbTGeHlxs36vT70Utubv5hA5lpbSKTXDVONtdjKyoaWhNEPXzHw17QQDVfOXD5B+ZGPZV6MI8XrgP47/8hiR5xxlp7dX6s7IZvZVsfrqKOLntOnC/2CTlsRrXhykSae+8K+geR4HVFJxSnqMhu4glgxKTPdCFyFH8Ludf82xnSwJM5uGDf5JzYwMzgr58PFqXue8MitBZhkEevSfPY6fN35yUUzVIrbRq7zAtLu34HQP7jWzn4LKHfivDWc10qDOtpqNeMCFbG9vfvlnM6/HliKk4B2ZnHqbD9fi7ZOF/cZzfGYqpd8+CN1g6GoRWXxaMgaXYGSzWARFCyuslcJ/Z1wONPZ1dj7DPizQa8SjigJ7/ZcVdqiclng2SSDsuM7yypiWR9C2eE7dAS
  template:
    metadata:
      creationTimestamp: null
      name: flux-huggingface
      namespace: ai
