---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-database
  namespace: ai
spec:
  encryptedData:
    DATABASE_URL: AgCVJyOQh6TGSmJKebTyr3Y9OWJyV+7wLysfPgrnLAbNZAq1Mj6w4PfZC/32MQkRDLHUINIHcoGwMW4ptn9SyjyKFRcjs4AjhBbpnPH/jkAo5LR8oMprgK+8+H5g+gx4lZ/NNKuqz+4YEXALbbpjZ7X5S17j95IDx/CXQIfgU3P33Oe5nmkTzF3AHZ9KvhDQuEVi84YHGNZfrHvdmTlVGLuFC7FCYLYkK3+QbkGNc9QLMkP+1JdfTdHqWzmZkibYTpJU5L1EI3aLRgoqgRdaCWM1DCACV51Hu9RuThl2OqfFSfx2CJ23jjyO36eLMVz+ZnjF2yHtLsDyhuwoWHB9FLHd9ZGRpsekUdymKt249rsbQJf1kB+gyHrapQaaqlmBmGdomCU0ENjnrdlVwzIyRIWPNKxoEouJYZZxxvWawaPxR4A8KWnwtN3/hOs6ycQApOVCLTDCvai2TmtElSvRax2STHbD/n+LSXxPdWCFSjnjzFMKxxOCEhufCkgaZwUVbR3p/qD+UJlm/CX7B2pmsnwvrjC0RCFkXVh1FWOl0y++tXCUVCb0Qupr1KI4KuhiXgBU3q4K8o/2mO9A55L8DyGPnqhu1c6yZ4+l1ZSwsdOLPXknDw7vyOsWUBx7kj5OSbs0Z9WOD8U0L9nQ6QWlEz5i7LOK2v7AL/JmFZoVx1VPWCzvkupwEPtZpKYJLBWr6YyFHqtiN6B92pstF8QLsKwrpX+FbaBQf18htIGHarlubiShLmczBHce/q7T6plmdEZVo97dG2dW/wMnr8WHScTUqCXF/kUEckW1fQV9WTrkgwSoCic5+aDh80IFI6dEs0S1YYzoys5X4dpU2Zp5lqhgVT0=
  template:
    metadata:
      creationTimestamp: null
      name: litellm-database
      namespace: ai
