---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oci-registry-client
  namespace: ai
spec:
  encryptedData:
    password: AgCJzl9rDE75ZP1NF2Exq7PgU/LrNqZ15PaoWEd7IAYVb/mu/KNIiS109M9RCGuhKAItAIZFM4MdRbjNdghTt09nmJBthSz4Kz0k0xCypt4HIyDAW1FPxy5xkmqPoUNLgwcETKrl+vlDucLglhwaIDUzMnNkdJpcDODCdfZT7FJO0D4rRzWAs16cQ8vGxWBqyj/Ohr5n+UE7YYInPh95BMY7+eV13Hbuj8oI4UJQPlNzXzJg0L34h3mwBO7XMhThYN08k276xO/54V8WCYxyIPROwJEZ36jm8KtKBpaEfQF4Q5I7qlISyV66l9d3NC/QbMLMsbeUGAu/UspcBbkaxRWVhG9dEuFURasDj0PS1sCJnpHG0lJG/snucCyzDWLb1EH2onoa6/ZzWh6jMYn7QZ56GV8DhkG+j8BTZQiig7lsx68TNM8iiJITfXSk4tUyo+Cl1/W9TYMS4wDTKqRF+CUEMc+OTf3ZSRc1g6xuPGUaWOJ8+y4GJUNcgiBdyrsBoDFWea9q1faXITEf1Ga0Qqu8P/LmtR/EHu0ZW5i2WvZb8wSi98qADb/Y6/xpb5mSMNRYjYEHGwzJ75ntC+GSrGhzRU7bd7eZZGktEvq1jgwGBEvvAC4H6w4CKzjWl5ubtVMazOs8yMZy6E8unUfv/xkoPMuIUlWbTrckZGButiqrbvSDPbJmS/Rk5eIPs+exoanlnOzR1qAS9am9fAr6X/GUgBnDQ686ghzEubkgrslwgEEvrdtGSScy
    username: AgC6Q06OVfe6wvBo/DThRtzNoBbsEmTtNzr2rfi5F3IEweMrfa3Fzj9HTasBxfqxa3nmFMU7+k1jrw4AsNw41zd1kexuokSbWtcGkzu83GVyHwEPJ1sCdArRuuOm6qZU2MnOmKmB+Fm6Jqs3FaSFDfpUAUHVyGGDidA78bKI2HaVh9H1QIS1CNqVYpESfX5iVAXWwQS3pK2YJSpGHHBjeBNEo/m9wPI4wL+h1MzLrS9N0+phhqxDviiMs1cqIBLlsPSBGSAMmAj9thXfXuZjIwC0yWVB8ZsKK92Xia8Q4Yz8ucJsB6VKOXjOsNmdwxlM+NS9+kdQUuVDghemikk3uYFGgVwCpIL97M2uSPjnk08rp6TIdfK2ET/4nDIj0oLGtoOVtMNoqWLs3Daa36BgGZgV5i0uS2dtrmrR+A8p7XrCHoZ9IBb40h8CSTFUjhT0o1CdbEHOBsMqSwq8n94VDaZtZY5vOu5Nft3ZZbhYP/b0jnX/YMLfL70VWwM172FQQf7Ag4f/7o7RQdNO+lm0ETx9L03npxVDKQXvOgP5arFy5pWHaFzQc5Aocf7eFk8Z2o9b+MevudMYq3dsJLVx1xBti7xi5EoXorwb3whm0L6hjy3zEZ1kJkNzO9190z02ggDg/iJL1e1J5y+bv/PSaNgXe+hapyVibp/c+KdoIEXMo34Pi1HNY1v3sVcIZ1pvUrKTajQHfAB5RQ==
  template:
    metadata:
      creationTimestamp: null
      name: oci-registry-client
      namespace: ai
