---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oci-registry-pull
  namespace: ai
spec:
  encryptedData:
    .dockerconfigjson: AgC591bwk40bCPB5P3ond5U7eOO7ffqOHwqp0rgWHRuqsHQDqei/jpOUxVnlZ5AsNoPCCC5vHGdSBrlBQtwvGUtSqQlio3SDoF5ju4+WvNe04zgOcHOQ7tGMCnmVdJGvccSUhvxUizTNTJuHYu6EXf/lLOodMqlTEea/qsYuhBDKUXggepbtqFdnRHMXi0ejR+nHH3Re9kSYhIH8qmIe9cQd1Ej2cnY0C8ZpKiRBQ/VFmtoY2b7lqpf6gd3ZBU6qm10WM2ACRZv6wOsF7esyNAONZZXj7nVtWaM2DwBmS7+kTphUzHwCiHQg14JNlmctB5ZoPQmFUqu/gC5ZR7MVg8srZQf+L99K0xQAA92/xldIL/GwA6NgupCneZuI8wjv2aH1DnSKflDiUnc4cMdlKgaDKNp2MoKXxIHB6XxSgLH2oiBxDah6cWjg7gtLyPTFoQn0hBgAC+I+t0yOwP+vsBvVR5pB2+P49XuyAULEIuLztq3OqOLL96RTIJnsRH4ovcNKeiJzYygONB9uDGWMpSpUh0eq7Yo8AYjAicW515F6RkvTR8uPDAUk0cGx1LXKaTbNmC8PeFLqGK7hkrm4dwvOm+pSMh0cvcglEQcON+XJhO5sQrRou6kgNpkMNOS6kN89u43NXAjdXrda4oZYCIl1wjfj6zMGYdbmgwbonPaYQVWc3zF6sS7ZDs1FL0aesU0vBnl9nKV8pzeo7+MH/RnvTx39ITtZ9QgvMAFbJ15YcumxalhXoMEaEQ/jQZ2SmMypsaMfrcBbIqpD6PoAmajxlXrkqID0UeEGn7356VTKIBeRZfheRJLvNOMVz0x0Rwva3JqHMvne3oHLBEay8KM6hlNawS3karzYr/8OuzwaPu5QeMMhBWCPIZ2HflQsLaxPcVmsnxnMN65yy017dJ5sx1OD9T4RuqVxjeEmaHX9ySi6RJUkylOP9lJs5iA=
  template:
    metadata:
      creationTimestamp: null
      name: oci-registry-pull
      namespace: ai
    type: kubernetes.io/dockerconfigjson
