apiVersion: v1
kind: ResourceQuota
metadata:
  name: model-evals
  namespace: model-evals
spec:
  hard:
    pods: "3"
    requests.cpu: "24"
    limits.cpu: "24"
    requests.memory: 128Gi
    limits.memory: 128Gi
    requests.nvidia.com/gpu.shared: "1"
    limits.nvidia.com/gpu.shared: "1"
