apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oci-zot-data
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-nfs
  resources:
    requests:
      storage: 500Gi